# Generated by Django 6.0.6 on 2026-06-06 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('rumah', 'Rumah'), ('ruko', 'Ruko'), ('gudang', 'Gudang')], max_length=20)),
                ('listing_mode', models.CharField(choices=[('rent', 'Rent'), ('sell', 'Sell')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('width', models.DecimalField(decimal_places=2, max_digits=8)),
                ('length', models.DecimalField(decimal_places=2, max_digits=8)),
                ('floors', models.PositiveIntegerField(default=1)),
                ('area', models.CharField(max_length=100)),
                ('owner_whatsapp_number', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.property')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
