# Generated by Django 6.0.6 on 2026-06-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='block',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(fields=('property_type', 'area', 'block', 'unit_no'), name='unique_property_unit_identifier'),
        ),
    ]
