# Generated by Django 6.0.6 on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_property_block_property_unit_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyphoto",
            name="image",
            field=models.FileField(upload_to="property_photos/"),
        ),
    ]
